### ISSUE TITLE
please read the lastest news message in the official chocolet server.

### ISSUE THREAD

**Issue by Githubman6996** [notalicialol/Chocolet#7]
please read the lastest news message in the official chocolet server.

_Originally posted by @notalicialol in https://github.com/notalicialol/Chocolet/issues/6#issuecomment-2211399107_
            
            
What’s the chocolot server link

**Comment by Githubman6996** [comment]
@notalicialol

**Comment by notalicialol** [comment]
please stop making issues that are very irrelevant. the link to join our current offical server is https://discord.gg/REeNuu8svr. again, please stop opening issues, the site is under development so no issues are relevant at this moment.
